export const routes = {
  welcome: "/welcome",
  bloodCentreRegister: "/blood-centre/register",
  bloodCentreVerify: "/blood-centre/verify",
  bloodCentreLogin: "/blood-centre/login",
  bloodCentreDashboard: "/blood-centre/dashboard",
  addAvailability: "/blood-centre/availability/add",
  availability: "/blood-centre/availability",
  donor: "/donor",
  donorRegister: "/donor/register",
  donorVerify: "/donor/verify",
  donorLogin: "/donor/login",
  donorDashboard: "/donor/dashboard",
  donorAvailability: "/donor/availability",
  recipient: "/recipient",
  recipientVerify: "/recipient/verify",
  recipientRegister: "/recipient/register",
  recipientSearch: "/recipient/search",
  superAdminDashboard: "/super-admin/dashboard",
} as const;
