export const routes = {
  welcome: "/welcome",
  bloodCentreRegister: "/blood-centre/register",
  bloodCentreLogin: "/blood-centre/login",
  bloodCentreForgotPassword: "/blood-centre/forgot-password",
  bloodCentreResetPassword: "/blood-centre/reset-password",
  bloodCentreDashboard: "/blood-centre/dashboard",
  addAvailability: "/blood-centre/availability/add",
  availability: "/blood-centre/availability",
  donor: "/donor",
  donorRegister: "/donor/register",
  recipient: "/recipient",
  recipientRegister: "/recipient/register",
  recipientSearch: "/recipient/search",
  superAdminDashboard: "/super-admin/dashboard",
} as const;
